### ISSUE TITLE
Can you kindly include a demo .env  (both us.env and ms.env) files with readme.md ?

### ISSUE THREAD

**Issue by shamim-42** [abdelhadinaimi/nest-microservices#10]
After running the docker-compose up services can't connect with mongodb

**Comment by abdelhadinaimi** [comment]
Hello,
I lost the original .env files but it should look like this for ms.env and us.env :
``` 
PORT=
REDIS_HOST=
REDIS_PORT=
MONGO_HOST=
MONGO_PORT=
MONGO_USER=
MONGO_PASS=
MONGO_NAME=
```

**Comment by shamim-42** [comment]
> Hello,
> I lost the original .env files but it should look like this for ms.env and us.env :
> 
> ```
> PORT=
> REDIS_HOST=
> REDIS_PORT=
> MONGO_HOST=
> MONGO_PORT=
> MONGO_USER=
> MONGO_PASS=
> MONGO_NAME=
> ```

I have spent a lot of times already on your project. This is an exciting helpful repository for microservice project starter. I am running it as docker container now. I was fetching some problems related with docker and then edited Dockerfiles.

### **Here are the edited dockerfiles for the future users.**
**api folder**
```
FROM node:12
WORKDIR /app/apiservice

COPY package.json package-lock.json /app/apiservice/

# RUN npm cache clean --force && npm install -g npm@latest && npm install --no-optional
RUN npm install --no-optional

COPY . /app/apiservice

RUN npm run build

CMD [ "npm", "start" ]
```


**media-services folder**
```
FROM node:12
WORKDIR /app/mediaservice

COPY package.json package-lock.json /app/mediaservice/

RUN npm cache clean --force && npm install --no-optional

COPY . /app/mediaservice/

RUN npm run build
CMD [ "npm", "start" ]
```

**user-management-services folder**
```
FROM node:12
WORKDIR /app/userservice

COPY package.json package-lock.json /app/userservice/

RUN npm cache clean --force && npm install --no-optional

COPY . /app/userservice/
RUN npm run build
CMD [ "npm", "start" ]
```

### **.env files**
**us.env**
```
REDIS_HOST=redis
REDIS_PORT=6379
MONGO_URI=mongodb://us-mongodb:27017/
MONGO_PORT=27018
```

**ms.env**
```
REDIS_HOST=redis
REDIS_PORT=6379
MONGO_URI=mongodb://us-mongodb:27017/
MONGO_PORT=27018
```
`us-mongodb` is the service name of the docker-compose file.


Another comment to say:  The post api to create any user shouldn't apply the token based authentication. If so then how someone can signup ?

**Comment by abdelhadinaimi** [comment]
Thank you @shamim-42 can you make a pull request so I can add it to the project?
And for user auth I didn't have time to do it, the token is provided by Auth0 when you register, there are tutorials on their website on how to setup a registration workflow.

**Comment by shamim-42** [comment]
Dear @abdelhadinaimi,
I have created a pull request. Please take a look on and can merge codes with existing. I hope this will give ease to the future user of this repository to run this project Ingsha Allah.

**Comment by abdelhadinaimi** [comment]
Thanks @shamim-42 for the changes, I kind of abandoned this project, I didn't have a lot of time to fix the deployment issues.

Edit: Aid Moubarak

**Comment by shamim-42** [comment]
Eid Mubarak !
